gText_Birch_Welcome::
	.string "Welcome to the world of POKéMON.\p"
	.string "You are a spirit awakened in\n"
	.string "response to the calamity.\p"
	.string "In your time here in Piritos,\n"
	.string "you will be journeying to find yourself\l"
	.string "and become a brand new POKéMON.\p"
	.string "Pokemon are mysterious creatures that\n"
	.string "share the world with humans who\l"
	.string "often act as their companions and\l"
	.string "trainers.\p"
	.string "You may find--\n"
	.string "You are sure to find humans and\l"
	.string "POKéMON on your journey, and the\l"
	.string "choices you make will shape you into\l"
	.string "your new form.\p"
	.string "You have awakened in Piritos.\n"
	.string "It’s known for STUFF.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Speech Part 2\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Speech Part 3\n"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
