SpiritTown1_MapScripts::
	.byte 0

SpiritTown1_EventScript_Route1Girl::
	msgbox SpiritTown1_Text_Route1Girl, MSGBOX_NPC
	end

SpiritTown1_Text_Route1Girl:
	.string "Traveling is wonderful!\p"
	.string "When I was young, I roamed the seas\n"
	.string "and the mountains!$"

SpiritTown1_EventScript_Route2Girl::
	msgbox SpiritTown1_Text_Route2Girl, MSGBOX_NPC
	end

SpiritTown1_Text_Route2Girl:
	.string "Sigh…\p"
	.string "I wish I could go on an adventure\n"
	.string "with some POKéMON…\p"
	.string "Crawl through some damp grass…\n"
	.string "Climb rocky, rugged mountains…\p"
	.string "Cross the raging seas…\n"
	.string "Wander about in dark caves…\p"
	.string "And, sometimes, even get a little\n"
	.string "homesick…\p"
	.string "It must be fabulous to travel!$"

SpiritTown1_EventScript_Route3Boy::
	msgbox SpiritTown1_Text_Route3Boy, MSGBOX_NPC
	end

SpiritTown1_Text_Route3Boy:
	.string "Sigh…\p"
	.string "I wish I could go on an adventure\n"
	.string "with some POKéMON…\p"
	.string "Crawl through some damp grass…\n"
	.string "Climb rocky, rugged mountains…\p"
	.string "Cross the raging seas…\n"
	.string "Wander about in dark caves…\p"
	.string "And, sometimes, even get a little\n"
	.string "homesick…\p"
	.string "It must be fabulous to travel!$"

